### ISSUE TITLE
Make options for hidden input configurable

### ISSUE THREAD

**Issue by eluhr** [germanbisurgi/jedi#1]
We need a way to change the name xor id attribute for the hidden input. As far as I can see, two instances of the editor cannot currently exist, as the same id is always set for the input.

→ [hard coded id attribute](https://github.com/germanbisurgi/jedi/blob/main/src/jedi.js#L186)
→ [hard coded name attribute](https://github.com/germanbisurgi/jedi/blob/main/src/jedi.js#L190)

CC: @schmunk42 @germanbisurgi

**Comment by germanbisurgi** [comment]
Just added a new option `hiddenInputAttributes`. 

```javascript
new Jedi.Create({
  //...
  hiddenInputAttributes: {
    name: 'my-name',
    id: 'my-id'
  }
  // ...
})
```
